// Re-encode oversized images in public/, in place.
//
// The asset tree had a 3.8 MB JPEG in it and several PNGs over a megabyte —
// enough that a first visit on a phone was downloading more image bytes than
// the rest of the site combined.
//
// Two rules, both chosen to avoid touching a single reference:
//
//   - Formats and filenames never change. Published transmissions are
//     append-only (see BLOG_ROADMAP.md), so rewriting an .mdx to point at a
//     .webp would be an edit to a published post. Recompressing the bytes
//     behind the same URL is not.
//   - Nothing is upscaled. Each file is capped at the width it actually
//     renders into (see CAPS) times three, so a dense display still has more
//     pixels than it can show.
//
// JPEGs go through mozjpeg; PNGs are quantised to a palette when they survive
// it (the Media illustrations are line art and lose nothing), and left as
// full-colour PNG when they don't. A file is only written back if it actually
// got smaller.
//
// Run it after adding heavy art, then commit the result:
//   node scripts/optimize-images.mjs [--dry]

import sharp from 'sharp';
import { readFile, writeFile, stat } from 'node:fs/promises';
import { glob } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve('public');

/**
 * Only touch files above this — recompressing a 30 KB icon buys nothing. A file
 * wider than its cap is touched whatever its size, though: the size threshold
 * alone let a 222 KB, 960px Instagram icon through to be drawn at 16px, because
 * it sat just under the line.
 */
const MIN_BYTES = 250 * 1024;

/**
 * Never touched. og/ and og-card.png are regenerated by capture-og-cards.mjs,
 * and buttons/ by make-buttons.mjs, whose srihith@2x.png is the lossless source
 * the 1x is resampled from — quantising it would degrade every future build.
 */
const SKIP = /^(og[/\\]|og-card\.png$|buttons[/\\])/i;

/**
 * Default cap: the prose column is 800px, so 1600 covers it on a 2x display.
 * Applies to blog art, which is the only thing here that goes full width.
 */
const MAX_WIDTH = 1600;

/**
 * Per-file caps for images whose render box is far smaller than the default.
 * Aristotle.jpg is the reason this table exists: a 2290x3250 scan being poured
 * into a 160px-wide container, which is 3.8 MB to draw a thumbnail. Each number
 * is the CSS box from the stylesheet, times three for dense displays.
 *
 * Measured in the browser at 390, 1440 and 1920 wide where the stylesheet does
 * not make the box obvious. An image sized `height: auto` decides the height of
 * everything below it, so its cap is chosen to divide both sides exactly — a
 * ratio off by a fraction of a pixel moves the rest of the page.
 */
const CAPS = [
  [/^Aristotle\.jpg$/i, 480], // .quote-image-container — 160px
  [/^crest\.png$/i, 144], // .crest-icon — 48px square
  [/^smlogos[/\\]/i, 48], // contact icons — 16px square
  [/^Kepler\.png$/i, 357], // .kepler-link — 150px, height auto; 476x524 is 119x131 x4
  // .media-plate__art img — clamped to 116px tall, which draws the widest
  // (Books) at 154px. The old 720 assumed 68% of the plate's width won.
  [/^Media[/\\]/i, 480],
  // Project previews, object-fit: contain in a 168px-tall box. filter.png is a
  // portrait phone shot, so that box draws it 94px wide.
  [/^filter\.png$/i, 300],
  [/Preview\.png$|^KrineLogo/i, 1000], // project cards — ~380px
  // Card art, drawn at most 366px wide. fi99 is the featured card, drawn up to
  // 658px, so it stays on the default.
  [/^projects[/\\](?!fi99)/i, 1100],
  [/^(lightmode)?figure\.(png|jpg)$/i, 1100], // .hero-figure — 550px max
];

function capFor(rel) {
  for (const [pattern, width] of CAPS) if (pattern.test(rel)) return width;
  return MAX_WIDTH;
}

const JPEG_QUALITY = 82;

const dry = process.argv.includes('--dry');

function kb(n) {
  return `${Math.round(n / 1024)} KB`;
}

async function candidates() {
  const out = [];
  for await (const f of glob('**/*.{jpg,jpeg,png,jfif}', { cwd: ROOT })) {
    if (SKIP.test(f)) continue;
    const abs = path.join(ROOT, f);
    const { size } = await stat(abs);
    const { width = 0 } = await sharp(abs).metadata();
    if (size >= MIN_BYTES || width > capFor(f)) out.push({ rel: f, abs, size });
  }
  return out.sort((a, b) => b.size - a.size);
}

/** Re-encode one buffer, keeping its format. Returns the best buffer found. */
async function reencode(buf, ext, rel) {
  const img = sharp(buf, { animated: false });
  const meta = await img.metadata();
  const cap = capFor(rel);

  // Only ever shrink.
  const resized =
    meta.width && meta.width > cap
      ? img.resize({ width: cap, withoutEnlargement: true })
      : img;

  if (ext === '.png') {
    // Try a palette first; it is dramatic on flat art and bad on photographs,
    // so keep whichever comes out smaller.
    const [palette, full] = await Promise.all([
      resized.clone().png({ palette: true, quality: 82, effort: 9 }).toBuffer(),
      resized.clone().png({ palette: false, compressionLevel: 9, effort: 10 }).toBuffer(),
    ]);
    return palette.length <= full.length ? palette : full;
  }

  // .jpg / .jpeg / .jfif — all JPEG containers, so mozjpeg applies to each.
  return resized
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true, progressive: true })
    .toBuffer();
}

async function main() {
  const files = await candidates();
  if (!files.length) {
    console.log(`nothing in public/ is over ${kb(MIN_BYTES)}`);
    return;
  }

  let before = 0;
  let after = 0;

  for (const { rel, abs, size } of files) {
    const ext = path.extname(rel).toLowerCase();
    const buf = await readFile(abs);
    let out;
    try {
      out = await reencode(buf, ext, rel);
    } catch (err) {
      console.log(`${rel.padEnd(30)} SKIPPED — ${err.message.split('\n')[0]}`);
      continue;
    }

    before += size;

    if (out.length >= size) {
      after += size;
      console.log(`${rel.padEnd(30)} ${kb(size).padStart(8)}  already minimal`);
      continue;
    }

    after += out.length;
    const saved = Math.round((1 - out.length / size) * 100);
    console.log(
      `${rel.padEnd(30)} ${kb(size).padStart(8)} -> ${kb(out.length).padStart(8)}  -${saved}%${dry ? '  (dry)' : ''}`
    );
    if (!dry) await writeFile(abs, out);
  }

  console.log(
    `\ntotal ${kb(before)} -> ${kb(after)}  (-${Math.round((1 - after / before) * 100)}%)` +
      (dry ? '  [dry run, nothing written]' : '')
  );
}

main();
