/**
 * The 88x31 buttons in the footer.
 *
 * The PNGs are generated by scripts/make-buttons.mjs and committed — the list
 * of badges to draw lives in that script, and this file is what the site
 * renders. Adding or removing one means changing BOTH places: the script draws
 * it, this decides whether it is shown and where it points.
 *
 * Why any of this exists: the footer already carried a webring, and a webring
 * without a button is a business card with no name on it. The button is the
 * artifact the whole ring culture actually ran on.
 */

export type Button = {
  /** File in public/buttons, without the extension. */
  name: string;
  /** Alt text. These are images carrying words, so the words have to be here. */
  alt: string;
  /** Internal path or external URL. Decorative badges have no href. */
  href?: string;
  /** Tooltip, where the badge is drier than the joke behind it. */
  title?: string;
};

/** Where the canonical 88x31 lives, for anyone who wants to link here. */
export const OWN_BUTTON = {
  src: '/buttons/srihith.png',
  src2x: '/buttons/srihith@2x.png',
  alt: 'Srihith Jarabana — 88x31 button',
};

/**
 * The badges, in row order.
 *
 * Every one is either factually true of this site or plainly a joke; none of
 * them counterfeits a third party's mark. "No analytics" is the literal truth
 * (there is no analytics script in the bundle and the fonts are self-hosted),
 * and "valid vibes only" is the joke version of the W3C badge rather than a
 * forgery of it.
 *
 * The site's own button is inserted at the midpoint of these plus `neighbours`
 * (see ButtonWall), so it stays centred as the list grows. An odd total puts it
 * off-centre by half a button, which is the only reason to care how many there
 * are.
 */
export const badges: Button[] = [
  {
    name: 'no-analytics',
    alt: 'No analytics — nobody is watching',
    title: 'no analytics script, no third-party fonts',
  },
  { name: 'best-viewed', alt: 'Best viewed with your eyes' },
  { name: 'valid-vibes', alt: 'Valid vibes only' },
  { name: 'made-in', alt: 'Made in Canada' },
];

/**
 * Buttons for other people's sites.
 *
 * Empty on purpose rather than seeded: a button wall is a list of people you
 * actually read, and inventing one would make it a decoration instead of a
 * link. Drop a copy of their 88x31 in public/buttons/ (host it here — hotlinking
 * spends someone else's bandwidth and dies when they reorganise) and add a row:
 *
 *   { name: 'their-button', alt: 'Their Site', href: 'https://example.com' }
 */
export const neighbours: Button[] = [];
